# image will be published to ghcr.io/<user>/<name>
name: seiketsu
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.
  - type: script
    scripts:
      - enable-openh264.sh
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/repo/fedora-%OS_VERSION%/zeno-scrcpy-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/sentry/kernel-fsync/repo/fedora-%OS_VERSION%/sentry-kernel-fsync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/obs-vkcapture/repo/fedora-%OS_VERSION%/kylegospo-obs-vkcapture-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/che/nerd-fonts/repo/fedora-%OS_VERSION%/che-nerd-fonts-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-addons-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - perl
      - perl-CPAN 
      
      - python3-pip
      - python3

      - docker-compose

      # Fcitx input
      - fcitx5-mozc
      - fcitx5-configtool
      - fcitx5-autostart
      - fcitx5-qt
      - fcitx-qt5
      - kcm-fcitx5
      # - fcitx5-configtool
      - imsettings

      - mecab 
      - mecab-ipadic

      - rclone
      - ffmpeg
      - mozilla-openh264
      - openh264
      - AtomicParsley
      - kdeplasma-addons
      - xwaylandvideobridge

      - git
      - curl

      - cmake
      - cmake-data
      - clang
      - clang-tools-extra
      - jq
      - mold

      - fira-code-fonts
      - google-noto-sans-fonts
      - google-noto-cjk-fonts 
      - liberation-fonts
      - mscore-fonts-all
      - tokei
      - ripgrep

      - yt-dlp 

      - scrcpy

      - easyeffects

      - xeyes

      - scx-scheds

      - gamescope
      - mangohud
      - VK_hdr_layer

      - mpv
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - noopenh264 

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    user:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install: 
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

